global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "bank-transfer-system-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8091", "host.docker.internal:8092"]
        labels:
          application: "bank-transfer-system"
