spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6380

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_transfers_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6380"
      timeout: 10000
      connectionPoolSize: 10
      connectionMinimumIdleSize: 1

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key-id: test
      secret-key: test
    sqs:
      endpoint: http://localhost:4568
      listener:
        auto-create-queue: false
