spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_transfers_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

aws:
  access-key-id: test
  secret-key: test
  region: us-east-1
  kinesis:
    endpoint: 'http://localhost:4568'
    streams:
      internal-transfers:
        requested:
          stream-name: bank-transfer.internal.requested
        failed:
          stream-name: bank-transfer.internal.failed
        completed:
          stream-name: bank-transfer.internal.completed