server:
  port: 8092

spring:
  application:
    name: bank-transfer-processing-service

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  #TODO adjust it for production
  jpa:
    hibernate:
      ddl-auto: create-drop  # For dev/testing only; use 'update' or 'validate' in production
    show-sql: false

aws:
  region: ${AWS_DEFAULT_REGION}
  kinesis:
    streams:
      internal-transfers:
        requested:
          stream-name: bank-transfer.internal.requested
        failed:
          stream-name: bank-transfer.internal.failed
        completed:
          stream-name: bank-transfer.internal.completed

client:
  api:
    bank-accounts:
      base-url: 'http://localhost:8090'

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    distribution:
      percentiles-histogram:
        request.internal.transfer.time: true