server:
  port: 8091

spring:
  application:
    name: bank-transfer-request-service
  cache:
    type: redis
    cache-names: bank-transfer-requests
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

redisson:
  config: |
    singleServerConfig:
      address: "redis://${REDIS_HOST}:${REDIS_PORT}"
      timeout: 10000
      connectionPoolSize: 10
      connectionMinimumIdleSize: 1

cloud:
  aws:
    region:
      static: ${AWS_DEFAULT_REGION}

management:
  endpoints:
    web:
      exposure:
        include: prometheus #, health, metrics
  metrics:
    distribution:
      percentiles-histogram:
        request.internal.transfer.time: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

api:
  v1:
    bank-transfers:
      root-path: '/api/v1/bank-transfers'


