aws:
  access-key-id: test
  secret-key: test
  region: us-east-1
  kinesis:
    endpoint: 'http://localhost:4568'
    streams:
      request-internal-transfers:
        stream-name: bank-transfer.internal.requested