server:
  port: 8091

spring:
  application:
    name: bank-transfer-request-service

aws:
  region: ${AWS_DEFAULT_REGION}
  kinesis:
    streams:
      request-internal-transfers:
        stream-name: ${REQUEST_INTERNAL_TRANSFERS_KINESIS_STREAM_NAME}

management:
  endpoints:
    web:
      exposure:
        include: prometheus #, health, metrics
  metrics:
    distribution:
      percentiles-histogram:
        request.internal.transfer.time: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

api:
  v1:
    bank-transfers:
      root-path: '/api/v1/bank-transfers'


